template: "AxoAxonicCell"
template class: livn.models.ca1.neuron.templates.PRN_neuron.PRN
mechanism file:
  PinskyRinzel:
    Ltotal: 23.98186683654785
    V_rest: -64.0
    V_threshold: -40.0
    cm_ratio: 19.70673179626465
    dend_beta_Caconc: 0.010635889135301113
    dend_d_Caconc: 14.25243854522705
    dend_g_pas: 5.38151789442054e-06
    dend_gmax_Ca: 0.6601570844650269
    dend_gmax_KCa: 0.9620280861854553
    e_pas: -62
    gc: 48.11438751220703
    global_cm: 3.0
    global_diam: 10.0
    ic_constant: -0.01663380116224289
    pp: 0.28681623935699463
    soma_g_pas: 0.003669535042718053
    soma_gmax_K: 0.9987083673477173
    soma_gmax_Na: 0.5366288423538208
synapses:
  density:
    ## AAC synapse density configuration. Note this is the same as PVBC
    ## https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6782984/
    apical:
      excitatory:
        SLM:
          mean: 1.43
          variance: 0.1
        SR:
          mean: 4.16
          variance: 0.1
      inhibitory:
        SLM:
          mean: 0.27
          variance: 0.1
        SR:
          mean: 0.16
          variance: 0.1
    basal:
      excitatory:
        SO:
          mean: 3.61
          variance: 0.1
      inhibitory:
        SO:
          mean: 3.44
          variance: 0.1
    soma:
      inhibitory:
        default:
          mean: 0.18
          variance: 0.1
      excitatory:
        default:
          mean: 0.40
          variance: 0.1
