EXC:
  template: gEXC
  mechanism:
  synapses:
    density:
      ## PYR synapse density configuration.
      ## https://www.sciencedirect.com/science/article/pii/S0306452200004966?via%3Dihub
      apical:
        excitatory:
          SLM:
            mean: 0.90
            variance: 0.1
          SR:
            mean: 3.52
            variance: 0.1
        inhibitory:
          SLM:
            mean: 0.15
            variance: 0.1
          SR:
            mean: 0.11
            variance: 0.1
      basal:
        excitatory:
          SO:
            mean: 3.08
            variance: 0.1
        inhibitory:
          SO:
            mean: 0.11
            variance: 0.1
      soma:
        inhibitory:
          default:
            mean: 0.20
            variance: 0.1
        excitatory:
          default:
            mean: 0.0
            variance: 0.1
      ais:
        inhibitory: # Inhibitory https://www.ncbi.nlm.nih.gov/pubmed/20034063
          default: # layer
            mean: 0.68
            variance: 0.01
INH:
  template: gINH
  mechanism:
  synapses:
    density:
      ## PV Basket Cell (PVBC) synapse density configuration
      ## https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6782984/
      apical:
        excitatory:
          SLM:
            mean: 1.43
            variance: 0.1
          SR:
            mean: 4.16
            variance: 0.1

        inhibitory:
          SLM:
            mean: 0.27
            variance: 0.1
          SR:
            mean: 0.16
            variance: 0.1
      basal:
        excitatory:
          SO:
            mean: 3.61
            variance: 0.1
        inhibitory:
          SO:
            mean: 3.44
            variance: 0.1
      soma:
        inhibitory:
          default:
            mean: 0.18
            variance: 0.1
        excitatory:
          default:
            mean: 0.40
            variance: 0.1
