Definitions: !include _definitions.yml
Geometry:
  Parametric Surface:
    Layer Extents:
      SO: [[0.0, 0.0, 0.0], [40., 40., 10.0]]
      SP: [[0.0, 0.0, 10.0], [40., 40., 15.0]]
      SR: [[0.0, 0.0, 15.0], [40., 40., 35.0]]
      SLM: [[0.0, 0.0, 35.0], [40., 40., 45.0]]
  Cell Distribution:
    EXC:
      SO: 0
      SP: 7
      SR: 0
      SLM: 0
    INH:
      SO: 1
      SP: 2
      SR: 1
      SLM: 0
Connection Generator:
  Axon Extent:
    EXC:
      default:
        width: [1000.0, 1000.0]
        offset: [0, 0]
    INH:
      default:
        width: [1000.0, 1000.0]
        offset: [0, 0]
  Synapses: !include _synapses.yml
Cell Types: !include _cell_types.yml
